### ISSUE TITLE
程序出错

### ISSUE THREAD

**Issue by ByteStardust** [ydf0509/nb_http_client#3]
windows10
python3.11
使用本http库出现导包错误，已确认这些包已经全部安装
![image](https://user-images.githubusercontent.com/32776949/205480513-d6de9f71-5f2e-4ca1-87bb-c44b7c10b263.png)

**Comment by ydf0509** [comment]
seleiun版本高了。

**Comment by ByteStardust** [comment]
那应该使用那个版本？

**Comment by ByteStardust** [comment]
或者能更新http库，适应新的特性

**Comment by ByteStardust** [comment]
这个api接口有没有说明文档，设置代理，设置header，cookie，有没有requests.session功能

**Comment by FynnFbc** [comment]
https出现错误

2022-12-04 21:01:16 - _ObjectContext - "D:\Python\mobile\venv\Lib\site-packages\universal_object_pool\__init__.py:115" - __exit__ - CRITICAL - <class 'ssl.SSLError'>
Traceback (most recent call last):
  File "D:\Python\mobile\test.py", line 54, in <module>
    licaijiaoyu().start("13800000018")
  File "D:\Python\mobile\test.py", line 45, in start
    resp = conn.request_and_getresponse('GET', '/get')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\mobile\venv\Lib\site-packages\universal_object_pool\contrib\http_pool.py", line 39, in request_and_getresponse
    self.conn.request(method, url, body=body, headers=headers,
  File "C:\Python\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Python\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Python\Python311\Lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)

**Comment by ByteStardust** [comment]
大佬，这个是不是不能设置代理？

**Comment by ydf0509** [comment]
> 那应该使用那个版本？

高版本的selieum去掉了phantomjs支持了，这些报错就算你看不懂英文报错提示，你复制到百度 google网上很容易搜索的

**Comment by ydf0509** [comment]
> 这个api接口有没有说明文档，设置代理，设置header，cookie，有没有requests.session功能

cookie session 代理ip，自己去看http模块需要，这只举例性能。

代理ip一看你就是爬虫了，那cpu速度就不是最关键的了，你能对第三方网站每秒爬3000次吗不反扒吗？如果你无法自己学习python内置的http模块的用法，那就老老实实用requests爬虫就好了。

我这个主要是针对公司内部的http api调用，没有反扒和代理。

**Comment by ByteStardust** [comment]
明白了，cookie可以设置在headers中，使用代理ip可以无限制爬取，使用golang测试可以对网站做到每秒1w次，但是golang的http请求不稳定，线程多开还没python好

**Comment by ByteStardust** [comment]
看到你的自动收缩最强多线程后，没有去分析你的代码，还以为都是用C/C++编写的，我不知道还有底层的http网络请求，是我学识太浅薄了

**Comment by ydf0509** [comment]
> 看到你的自动收缩最强多线程后，没有去分析你的代码，还以为都是用C/C++编写的，我不知道还有底层的http网络请求，是我学识太浅薄了

这是从三方包requests调用urllib3，urllib3调用http分析得到的，并不是偶然看了谁写的文章才知道http模块。

**Comment by ydf0509** [comment]
> 看到你的自动收缩最强多线程后，没有去分析你的代码，还以为都是用C/C++编写的，我不知道还有底层的http网络请求，是我学识太浅薄了

你都爬虫了，还能一秒钟使用1万次代理吗？1秒钟100次算是非常牛逼的代理了。

**Comment by ByteStardust** [comment]
隧道代理，动态中转，请求无限制，入口ip固定不变，出口IP随机，每次请求都不一样，配置足够可以百万并发

**Comment by ydf0509** [comment]
> 隧道代理，动态中转，请求无限制，入口ip固定不变，出口IP随机，每次请求都不一样，配置足够可以百万并发

不可能的，阿布云就是隧道代理，每秒100次的套餐高达10万元年费，每秒5次的3600元年费。每秒100万次年费得需要10亿人民币，你有这么多钱？

**Comment by ByteStardust** [comment]
https://www.lunaproxy.com/
https://www.bright.cn/
https://www.luminatidaili.com/
这几个了解一下，按流量收费的

**Comment by ByteStardust** [comment]
www.lunaproxy.com 这个平台有个无限制套餐，虽然很贵，如果是长期高并发很划算
无流量限制，无IP限制
